---
title: "Step 01: Read and wrangle data"
output: rmarkdown::html_vignette
description: >
  How to read and reshape data for conjoint analysis
vignette: >
  %\VignetteIndexEntry{Step 01: Read and wrangle data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Test

```{r}
library(tidyverse)
library(projoint)
```

# Data with the flipped repeated tasks

```{r}
outcomes <- str_c("choice", seq(from = 1, to = 8, by = 1))
outcomes <- c(outcomes, "choice1_repeated_flipped")
out1 <- reshape_conjoint(.data = exampleData1, 
                         .idvar = "ResponseId", 
                         .outcomes = outcomes,
                         .outcomes_ids = c("A", "B"),
                         .alphabet = "K", 
                         .repeated = TRUE,
                         .flipped = TRUE)
```

# Data with the not-flipped repeated tasks

```{r}
outcomes <- str_c("choice", seq(from = 1, to = 8, by = 1))
outcomes <- c(outcomes, "choice1_repeated_notflipped")
out2 <- reshape_conjoint(.data = exampleData2, 
                         .idvar = "ResponseId", 
                         .outcomes = outcomes,
                         .outcomes_ids = c("A", "B"),
                         .alphabet = "K", 
                         .repeated = TRUE,
                         .flipped = FALSE)
```

# Data without the repeated tasks

```{r}
outcomes <- str_c("choice", seq(from = 1, to = 8, by = 1))
out3 <- reshape_conjoint(.data = exampleData3, 
                         .idvar = "ResponseId", 
                         .outcomes = outcomes,
                         .outcomes_ids = c("A", "B"),
                         .alphabet = "K", 
                         .repeated = FALSE,
                         .flipped = NULL)
```
