---
title: "Step 03: Estimate and correct MMs"
output: rmarkdown::html_vignette
description: >
  How to estimate and correct marginal means
vignette: >
  %\VignetteIndexEntry{Step 03: Estimate and correct MMs}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, message=FALSE}
library(projoint)
library(dplyr)
```


```{r}
outcomes <- paste0("choice", seq(from = 1, to = 8, by = 1))
outcomes <- c(outcomes, "choice1_repeated_flipped")
out1 <- reshape_conjoint(.data = exampleData1, 
                         .idvar = "ResponseId", 
                         .outcomes = outcomes,
                         .outcomes_ids = c("A", "B"),
                         .alphabet = "K", 
                         .repeated = TRUE,
                         .flipped = TRUE)
```


```{r}
d <- out1$data
```

# Test 1 (Profile-level MM)

```{r}
d_mm1 <- organize_data(d, "att1", c("level1"), "profile_level")

pj_estimate(d_mm1, "mm", "analytical")
pj_estimate(d_mm1, "mm", "simulation")
pj_estimate(d_mm1, "mm", "bootstrap")

pj_estimate(d_mm1, "mm", "analytical", .irr = 0.75)
pj_estimate(d_mm1, "mm", "simulation", .irr = 0.75)
pj_estimate(d_mm1, "mm", "bootstrap",  .irr = 0.75)
```


# Test 2 (Choice-level MM) 

NOT ignoring the left vs. right position

```{r}
d_mm2 <- organize_data(d, "att1", c("level1", "level3"), "choice_level")

pj_estimate(d_mm2, "mm", "analytical")
pj_estimate(d_mm2, "mm", "simulation")
pj_estimate(d_mm2, "mm", "bootstrap")

pj_estimate(d_mm2, "mm", "analytical", .irr = 0.75)
pj_estimate(d_mm2, "mm", "simulation", .irr = 0.75)
pj_estimate(d_mm2, "mm", "bootstrap",  .irr = 0.75)
```


# Test 3 Choice-level MM

Ignoring the left vs. right position

```{r}
temp1 <- organize_data(d, "att1", c("level1", "level3"), "choice_level")
temp2 <- organize_data(d, "att1", c("level3", "level1"), "choice_level")

data_for_irr <- bind_rows(
  temp1$data_for_irr,
  temp2$data_for_irr
) %>% 
  distinct()

data_for_estimand <- bind_rows(
  temp1$data_for_estimand,
  temp2$data_for_estimand %>% mutate(selected = 1 - selected)
)

d_mm3 <- list(
  "data_for_irr" = data_for_irr,
  "data_for_estimand" = data_for_estimand
)

pj_estimate(d_mm3, "mm", "analytical")
pj_estimate(d_mm3, "mm", "simulation")
pj_estimate(d_mm3, "mm", "bootstrap")

pj_estimate(d_mm3, "mm", "analytical", .irr = 0.75)
pj_estimate(d_mm3, "mm", "simulation", .irr = 0.75)
pj_estimate(d_mm3, "mm", "bootstrap",  .irr = 0.75)

```



