#' Create a projoint_qoi Object
#'
#' This function creates a \code{projoint_qoi} S3 object, specifying quantities of interest (QOI) for custom estimations.
#' It is typically generated by the \code{\link{set_qoi}} function.
#'
#' @param ... Named arguments specifying attributes and levels of interest for conjoint estimation.
#'
#' @return An object of class \code{projoint_qoi}.
#'
#' @keywords internal
projoint_qoi <- function(...) {
  structure(
    list(...),
    class = "projoint_qoi"
  )
}
