#' Save the attributes and levels, and their order, from a conjoint data set, to a CSV file.
#'
#' This function saves the labels for attributes and levels, which are generated by \code{\link{reshape_projoint}}, in a CSV file. This is an important step in reorganizing labels.
#' 
#' @import readr
#' @import dplyr
#' @param .data A \code{\link{projoint_data}} object
#' @param .filename The name of a CSV file to be saved
#' @return None
#' @export
save_labels <- function(
    .data,
    .filename
){
  
  level_id <- NULL
  attribute <- NULL
  level <- NULL
  
  (.data$labels %>% 
      dplyr::select(level_id, attribute, level) %>% 
      dplyr::arrange(level_id) %>% 
      dplyr::mutate(order = row_number())
  )%>%
    readr::write_csv(.filename)
}  