#' Save the original labels for attributes and levels in CSV
#'
#' This function saves the labels for attributes and levels, which are generated by `reshape_conjoint()`, in a CSV file
#' 
#' @import readr
#' @import tidyr
#' @import stringr
#' @import rlang
#' @import tidyselect
#' @param .data A `projoint_data` object
#' @param .filename The name of a CSV file to be saved
#' @return A CSV file
#' @export
#' @examples
#' library(projoint)
#' library(readr)
#' 
#' data("exampleData1")
#' head(exampleData1)
#'
#' # Write outcome column names
#' outcomes <- paste0("choice", seq(from = 1, to = 8, by = 1))
#' outcomes <- c(outcomes, "choice1_repeated_flipped")
#' 
#' # Reshape the data
#' reshaped_data <- reshape_projoint(
#'   .dataframe = exampleData1, 
#'   .idvar = "ResponseId", 
#'   .outcomes = outcomes,
#'   .outcomes_ids = c("A", "B"),
#'   .alphabet = "K", 
#'   .repeated = TRUE,
#'   .flipped = TRUE)
#' 
#' # Save a CSV file (Not Run)
#' # save_labels(reshaped_data, "data-raw/labels_original.csv")

save_labels <- function(
    .data,
    .filename
){
  readr::write_csv(.data@labels, .filename)
}  