name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - name: Install system dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install R dependencies
        run: |
          install.packages(c("devtools", "remotes"))
          devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: R CMD check --no-manual --as-cran .
