---
title: "04. Estimate and correct marginal means (MMs)"
output: rmarkdown::html_vignette
description: >
  How to estimate and correct marginal means
vignette: >
  %\VignetteIndexEntry{04. Estimate and correct marginal means (MMs)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, message=FALSE}
library(projoint)
library(dplyr)
```


```{r}
outcomes <- paste0("choice", seq(from = 1, to = 8, by = 1))
outcomes <- c(outcomes, "choice1_repeated_flipped")
out1 <- reshape_conjoint(.data = exampleData1, 
                         .idvar = "ResponseId", 
                         .outcomes = outcomes,
                         .outcomes_ids = c("A", "B"),
                         .alphabet = "K", 
                         .repeated = TRUE,
                         .flipped = TRUE)
```

# Test 1 (Profile-level MM)

```{r}
pj_estimate(.dataframe = out1$data,
            .attribute = "att1",
            .level = "level1",
            .structure = "profile_level",
            .remove_ties = TRUE,
            .repeated_task = TRUE,
            .estimand = "mm",
            .method = "analytical",
            .irr = NULL)
```

# Test 2 (Choice-level MM), ignoring the position

```{r}
pj_estimate(.dataframe = out1$data,
            .attribute = "att1",
            .level = c("level1", "level2"),
            .structure = "choice_level",
            .remove_ties = TRUE,
            .repeated_task = TRUE,
            .estimand = "mm",
            .method = "analytical",
            .irr = NULL, 
            .ignore_position = FALSE)
```

# Test 3 (Choice-level MM), NOT ignoring the position

```{r}
pj_estimate(.dataframe = out1$data,
            .attribute = "att1",
            .level = c("level1", "level2"),
            .structure = "choice_level",
            .remove_ties = TRUE,
            .repeated_task = TRUE,
            .estimand = "mm",
            .method = "analytical",
            .irr = NULL, 
            .ignore_position = TRUE)
```

